export * from "./course.graphql"
export * from "./post.graphql"
export * from "./auth.graphql"
export * from "./profile.graphql"
export * from "./accounts.graphql"
export * from "./reports.graphql"
export * from "./orders.graphql"
